name: Java Build

on: [push]

jobs:
  build-multi-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        java: ['8', '11', '15']
        include:
        - os: ubuntu-latest
          pipcache: ~/.cache/pip
        - os: macos-latest
          pipcache: ~/Library/Caches/pip
        - os: windows-latest
          pipcache: ~\AppData\Local\pip\Cache
    name: Build on ${{ matrix.os }} with Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}-1
    # can be further improved: https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
    - name: Cache Python packages 
      uses: actions/cache@v2
      with:
        path: |
          ${{ matrix.pipcache }}
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}-pipcache
    - name: Cache Transformers models
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/huggingface
        key: ${{ runner.os }}-transformers-models
    - name: Cache OAEI files # The check if the download server works as expected is in java_coverage where this cache is not enabled
      uses: actions/cache@v2
      with:
        path: |
          ~/oaei_track_cache
        key: ${{ runner.os }}-oaei
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install python dependencies
      run: pip install -r ./matching-ml/src/main/resources/requirements.txt
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn clean install